### ISSUE TITLE
SwiftGen does not have access to generate files

### ISSUE THREAD

**Issue by RomaJZ** [drspoton/swiftgen-plugin-spm#1]
SwiftGen plugin not working properly because it has no permission to save files in working directory. Could you please help me with this issue? Screenshot with the error below:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/35544719/164791807-d23c2cca-fab7-49b2-a472-5a30361d26aa.png">

**Comment by drspoton** [comment]
@RomaJZ can you share swiftgen config file?

**Comment by RomaJZ** [comment]
@drspoton 
<img width="485" alt="image" src="https://user-images.githubusercontent.com/35544719/164815521-1e42d340-da36-4264-b5f9-5d47f24c0a76.png">

**Comment by RomaJZ** [comment]
@drspoton So what do you think about this issue?

**Comment by drspoton** [comment]
```
output_dir: ${DERIVED_SOURCES_DIR}
```

**Comment by RomaJZ** [comment]
@drspoton When I put that line inside swiftgen.yml, swiftgen lint command outputs an error. Can you show me an example of your yml file, please?

**Comment by RomaJZ** [comment]
@drspoton I got it, but the question was about putting those generated files into source files folder, not Derived data folder. Do you know how to allow file write in source directory? I believe it is something related to that line "Deny file-write" in logs file
